### ISSUE TITLE
Ace Command Error

### ISSUE THREAD

**Issue by ozziest** [adonisjs/adonis-app-dev#1]
First of all, I am not sure this is the correct repo for the issue. 

After then create a new application, when I call ace command an error occurred;

```
/usr/bin/env: node --harmony_proxies: No such file or directory
```

I have tried `ln -s /usr/bin/nodejs /usr/bin/node` and `sudo apt-get install nodejs-legacy` but there is still the error.

**Comment by thetutlage** [comment]
Node is not inside your path, so you will have to troubleshoot more as it is a node specific error.

For now you can do

```
node --harmony_proxies ace <command>
```

**Comment by ozziest** [comment]
It works for me. Thank you! :+1:
